### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by icebob** [mrkmg/node-docker-test#1]
Hi,

i tried your app, but I got error every time every node version.
The error:
```
/bin/bash: -c: line 1: syntax error: Unexpected end of file
```
![image](https://cloud.githubusercontent.com/assets/306521/17083515/d4a0cde4-51a3-11e6-9c0e-f2b7f45d86ee.png)

**Comment by mrkmg** [comment]
Hey @icebob this is now fixed. Thank you for letting me know (this is what happens when I don't sleep).

**Comment by mrkmg** [comment]
Actually this is still an issue.

**Comment by mrkmg** [comment]
Okay, this is fixed now.

**Comment by icebob** [comment]
Thanks!
